spring.application.name=board
spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:tcp://localhost/~/test
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
server.port=80