package spring.board.chat.migration;

import org.h2.tools.RunScript;
import org.junit.jupiter.api.Test;

import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class ChatRoomMemberRoleMigrationTest {

    @Test
    void migratesOwnerToRoleAndRemovesOwnerColumn() throws Exception {
        try (Connection connection = DriverManager.getConnection(
                "jdbc:h2:mem:chat-role-migration;DB_CLOSE_DELAY=-1",
                "sa",
                ""
        )) {
            createLegacySchema(connection);

            var migration = getClass().getResourceAsStream(
                    "/db/manual/2026-09-19-chat-room-member-role-h2.sql"
            );
            assertNotNull(migration);
            RunScript.execute(
                    connection,
                    new InputStreamReader(migration, StandardCharsets.UTF_8)
            );

            try (Statement statement = connection.createStatement()) {
                try (ResultSet roles = statement.executeQuery("""
                        SELECT member_id, role
                        FROM chat_room_member
                        ORDER BY member_id
                        """)) {
                    roles.next();
                    assertEquals(1L, roles.getLong("member_id"));
                    assertEquals("OWNER", roles.getString("role"));
                    roles.next();
                    assertEquals(2L, roles.getLong("member_id"));
                    assertEquals("MEMBER", roles.getString("role"));
                }
            }

            try (ResultSet ownerColumn = connection.getMetaData().getColumns(
                    null,
                    null,
                    "CHAT_ROOM",
                    "OWNER_ID"
            )) {
                assertFalse(ownerColumn.next());
            }
        }
    }

    private void createLegacySchema(Connection connection) throws Exception {
        try (Statement statement = connection.createStatement()) {
            statement.execute("CREATE TABLE member (id BIGINT PRIMARY KEY)");
            statement.execute("INSERT INTO member (id) VALUES (1), (2)");
            statement.execute("""
                    CREATE TABLE chat_room (
                        id BIGINT PRIMARY KEY,
                        owner_id BIGINT NOT NULL,
                        created_at TIMESTAMP NOT NULL,
                        CONSTRAINT fk_chat_room_owner
                            FOREIGN KEY (owner_id) REFERENCES member(id)
                    )
                    """);
            statement.execute("""
                    CREATE TABLE chat_room_member (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        room_id BIGINT NOT NULL,
                        member_id BIGINT NOT NULL,
                        joined_at TIMESTAMP NOT NULL,
                        CONSTRAINT uk_chat_room_member_room_member
                            UNIQUE (room_id, member_id)
                    )
                    """);
            statement.execute("""
                    INSERT INTO chat_room (id, owner_id, created_at)
                    VALUES (10, 1, TIMESTAMP '2026-09-19 10:00:00')
                    """);
            statement.execute("""
                    INSERT INTO chat_room_member (room_id, member_id, joined_at)
                    VALUES
                        (10, 1, TIMESTAMP '2026-09-19 10:00:00'),
                        (10, 2, TIMESTAMP '2026-09-19 11:00:00')
                    """);
        }
    }
}
